// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvposUqwctYzJu5Dw7Sw0p7g-iZK3wBMo',
    appId: '1:501407060564:web:916ee6cd8f0f0d436793c1',
    messagingSenderId: '501407060564',
    projectId: 'ytchat-37c47',
    authDomain: 'ytchat-37c47.firebaseapp.com',
    storageBucket: 'ytchat-37c47.appspot.com',
    measurementId: 'G-8CGF7RPHBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLuCA0QxvlJqF5OivnU6niRY6xOicQ2A',
    appId: '1:501407060564:android:11f57ff1ad5993c66793c1',
    messagingSenderId: '501407060564',
    projectId: 'ytchat-37c47',
    storageBucket: 'ytchat-37c47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABRq5dvUnB95RbDHUcibukv9kunVW7GnI',
    appId: '1:501407060564:ios:662a9cca5556579d6793c1',
    messagingSenderId: '501407060564',
    projectId: 'ytchat-37c47',
    storageBucket: 'ytchat-37c47.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABRq5dvUnB95RbDHUcibukv9kunVW7GnI',
    appId: '1:501407060564:ios:662a9cca5556579d6793c1',
    messagingSenderId: '501407060564',
    projectId: 'ytchat-37c47',
    storageBucket: 'ytchat-37c47.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvposUqwctYzJu5Dw7Sw0p7g-iZK3wBMo',
    appId: '1:501407060564:web:2ddb31d7fc8aba186793c1',
    messagingSenderId: '501407060564',
    projectId: 'ytchat-37c47',
    authDomain: 'ytchat-37c47.firebaseapp.com',
    storageBucket: 'ytchat-37c47.appspot.com',
    measurementId: 'G-FYYWT9ZXHG',
  );
}
